### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by RaguCse**

### CODE REVIEW

**Review by KoushikVcti — COMMENTED** [review]
-

**Review by ganeshpaih24 — APPROVED** [review]

**Review by chethanvcti — COMMENTED** [review]
GOOD

**Review by 2002chaithra — APPROVED** [review]

**Comment by RaguCse** [comment]
> 

Thank you

**Review by SurakshaKeshava — APPROVED** [review]

**Review by chethanvcti — APPROVED** [review]
GOOD

**Review by evitadmello21 — APPROVED** [review]

**Comment by RaguCse** [comment]
> 
ok

**Pull request merged**
